baseURL = "https://thisguy.codes/"
languageCode = "en-us"
title = "ThisGuy"
description = "ThisGuy Codes"
theme = "paper"
disqusShortname = "thisguycodes"

enableGitInfo = true
googleAnalytics = "UA-55201469-1"

[params]
author = "Travis Johnson"
description = "ThisGuy Codes"
gtm_id = "GTM-PS8GQ4Z"
gtm_datalayer = "basic"

[markup.highlight]
codeFences = true
guessSyntax = true
style = "monokai"
noClasses = true
tabWidth = 4
lineNoStart = 1
lineNumbersInTable = true
lineNos = true
hl_Lines = ""
