baseURL = "https://thisguy.codes/"
languageCode = "en-us"
title = "ThisGuy"
description = "ThisGuy Codes"
theme = "paper"
disqusShortname = "thisguycodes"

sectionPagesMenu = "main"

enableGitInfo = true
googleAnalytics = "UA-55201469-1"

[markup.highlight]
codeFences = true
guessSyntax = true
style = "monokai"
noClasses = true
tabWidth = 4
lineNoStart = 1
lineNumbersInTable = true
lineNos = true
hl_Lines = ""
